-- Mock 사용자 데이터 30개
INSERT INTO users (sub, nickname, deleted, created_at, updated_at) VALUES
('kakao_dev001', '김개발자', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev002', '이프론트', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev003', '박백엔드', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev004', '최데브옵스', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev005', '정풀스택', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev006', '한모바일', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev007', '강웹개발', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev008', '조게임개발', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev009', '윤데이터', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev010', '신머신러닝', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev011', '문AI개발', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev012', '송클라우드', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev013', '배보안전문', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev014', '임QA엔지니어', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev015', 'UI/UX디자이너', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev016', '프로덕트매니저', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev017', '테크리드', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev018', '시니어개발자', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev019', '주니어개발자', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev020', '인턴개발자', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev021', '아키텍트', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev022', '스크럼마스터', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev023', '데이터엔지니어', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev024', '플랫폼엔지니어', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev025', '인프라엔지니어', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev026', '네트워크엔지니어', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev027', '시스템관리자', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev028', 'DBA전문가', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev029', '성능튜닝전문', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('kakao_dev030', '코드리뷰어', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Mock 질문 세트 데이터 30개
INSERT INTO question_sets (owner_user_id, title, description, version_number, parent_version_id, is_public, is_deleted, created_at, updated_at) VALUES
(1, 'Java 백엔드 면접 질문', 'Spring Boot와 JPA 중심의 백엔드 개발 면접 질문 모음', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'React 프론트엔드 면접', 'React, TypeScript, Next.js 관련 프론트엔드 면접 준비', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '알고리즘 코딩테스트 대비', '자주 출제되는 알고리즘 문제와 해결 방법', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'DevOps 엔지니어 면접', 'Docker, Kubernetes, CI/CD 파이프라인 관련 질문', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '데이터베이스 심화 면접', 'MySQL, PostgreSQL, 인덱싱, 쿼리 최적화', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '모바일 앱 개발 면접', 'Android, iOS 네이티브 개발 관련 질문', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '웹 보안 전문가 면접', 'OWASP Top 10, 보안 취약점 분석', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, '머신러닝 엔지니어 면접', 'Python, TensorFlow, PyTorch 관련 기술 면접', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, '클라우드 아키텍트 면접', 'AWS, Azure, GCP 클라우드 서비스 활용', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, '게임 개발자 면접', 'Unity, Unreal Engine 게임 개발 관련', 1, NULL, false, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, '네트워크 엔지니어 면접', 'TCP/IP, 라우팅, 스위칭 네트워크 기초', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'QA 테스트 엔지니어 면접', '자동화 테스트, 성능 테스트, 테스트 전략', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'UI/UX 디자이너 면접', 'Figma, Adobe XD, 사용자 경험 설계', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'IT 프로젝트 매니저 면접', '애자일, 스크럼, 프로젝트 관리 방법론', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, '시스템 관리자 면접', 'Linux, Windows Server, 서버 관리', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, '신입 개발자 기초 면접', '프로그래밍 기초, CS 기본 지식', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, '경력 개발자 심화 면접', '아키텍처 설계, 팀 리더십, 기술 의사결정', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, '스타트업 개발자 면접', '빠른 개발, MVP 구축, 기술 스택 선택', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, '대기업 개발자 면접', '대규모 시스템 설계, 안정성, 확장성', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, '인공지능 연구원 면접', '딥러닝, 자연어처리, 컴퓨터 비전', 1, NULL, false, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, '블록체인 개발자 면접', 'Solidity, 스마트 컨트랙트, Web3', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'IoT 개발자 면접', '임베디드 시스템, 센서 네트워크', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, '빅데이터 엔지니어 면접', 'Hadoop, Spark, 데이터 파이프라인', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, '사이버보안 전문가 면접', '해킹 방어, 포렌식, 보안 정책', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, '소프트웨어 아키텍트 면접', '마이크로서비스, 분산 시스템 설계', 1, NULL, false, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 'API 개발자 면접', 'RESTful API, GraphQL, API 설계', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, '성능 최적화 전문가 면접', '코드 최적화, 메모리 관리, 프로파일링', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, '테크 리드 면접', '기술 의사결정, 팀 관리, 코드 리뷰', 1, NULL, false, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, '풀스택 개발자 면접', '프론트엔드와 백엔드 통합 개발', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, '오픈소스 기여자 면접', 'GitHub, 협업, 커뮤니티 활동', 1, NULL, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Mock 질문 데이터 (각 질문 세트당 5-10개씩)
INSERT INTO question (content, question_type, expected_answer, created_at, updated_at) VALUES
-- Java 백엔드 면접 질문들 (질문 세트 1)
('Spring Boot의 Auto Configuration 원리에 대해 설명해주세요.', 2, 'Spring Boot는 @EnableAutoConfiguration을 통해 클래스패스의 jar 파일들을 스캔하고, spring.factories 파일에 정의된 설정 클래스들을 자동으로 로드합니다. @Conditional 어노테이션을 사용하여 특정 조건이 만족될 때만 자동 설정이 적용되도록 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JPA N+1 문제와 해결 방법을 설명해주세요.', 2, 'N+1 문제는 연관관계가 있는 엔티티를 조회할 때 발생하는 문제로, 첫 번째 쿼리로 N개의 데이터를 가져온 후 각각에 대해 추가 쿼리가 N번 실행되는 현상입니다. 해결 방법으로는 fetch join, @EntityGraph, @BatchSize 등이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Spring의 Bean Scope에 대해 설명해주세요.', 2, 'Bean Scope는 빈의 생명주기와 생성 범위를 정의합니다. singleton(기본값), prototype, request, session, application, websocket 등이 있으며, singleton은 컨테이너당 하나의 인스턴스만 생성되고, prototype은 요청시마다 새 인스턴스를 생성합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('REST API 설계 원칙에 대해 설명해주세요.', 2, 'REST API 설계 원칙으로는 1) 자원을 URI로 표현, 2) HTTP 메소드로 행위 표현, 3) 무상태성, 4) 계층화, 5) 캐시 가능성, 6) 일관된 인터페이스 등이 있습니다. URL은 명사로 구성하고, HTTP 상태 코드를 적절히 사용해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('트랜잭션의 ACID 속성을 설명해주세요.', 2, 'ACID는 데이터베이스 트랜잭션의 네 가지 속성입니다. Atomicity(원자성): 모든 연산이 성공하거나 모두 실패, Consistency(일관성): 트랜잭션 전후 데이터 무결성 유지, Isolation(격리성): 동시 실행 트랜잭션들이 서로 영향 없음, Durability(지속성): 커밋된 트랜잭션의 영구 보존입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- React 프론트엔드 면접 질문들 (질문 세트 2)
('React의 Virtual DOM이 무엇이고 왜 사용하는지 설명해주세요.', 2, 'Virtual DOM은 실제 DOM의 가벼운 사본으로, 메모리에 저장되는 JavaScript 객체입니다. 상태 변경 시 Virtual DOM에서 차이를 계산하고(diffing), 변경된 부분만 실제 DOM에 적용하여(reconciliation) 성능을 최적화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('useState와 useEffect 훅의 사용법과 주의사항을 설명해주세요.', 2, 'useState는 함수형 컴포넌트에서 상태를 관리하는 훅입니다. useEffect는 사이드 이펙트를 처리하며, 의존성 배열로 실행 조건을 제어합니다. 무한 루프 방지를 위해 의존성 배열을 정확히 설정하고, cleanup 함수로 메모리 누수를 방지해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('React에서 key prop의 역할과 중요성을 설명해주세요.', 2, 'key prop은 React가 리스트의 각 요소를 고유하게 식별하는 데 사용됩니다. 요소의 추가, 삭제, 순서 변경 시 효율적인 재렌더링을 위해 필요하며, 배열 인덱스보다는 고유한 값을 사용해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('TypeScript와 React를 함께 사용하는 이유와 장점을 설명해주세요.', 2, 'TypeScript는 정적 타입 검사를 제공하여 런타임 오류를 컴파일 타임에 발견할 수 있습니다. React와 함께 사용하면 컴포넌트 props의 타입 안정성, 자동완성, 리팩토링 용이성, 코드 가독성 향상 등의 장점이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('React 성능 최적화 방법들을 설명해주세요.', 2, 'React 성능 최적화 방법으로는 1) React.memo로 불필요한 리렌더링 방지, 2) useMemo와 useCallback으로 값과 함수 메모이제이션, 3) 컴포넌트 분할로 렌더링 범위 최소화, 4) 가상화로 대용량 리스트 처리, 5) 코드 스플리팅으로 번들 크기 최적화 등이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 알고리즘 코딩테스트 질문들 (질문 세트 3)
('시간복잡도와 공간복잡도의 개념을 설명하고 Big O 표기법의 의미를 설명해주세요.', 2, '시간복잡도는 알고리즘 실행 시간을, 공간복잡도는 메모리 사용량을 입력 크기에 따라 나타낸 것입니다. Big O 표기법은 최악의 경우를 기준으로 알고리즘의 성능을 점근적으로 표현하는 방법입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('배열과 연결리스트의 차이점과 각각의 장단점을 설명해주세요.', 2, '배열은 메모리에 연속적으로 저장되어 인덱스로 O(1) 접근이 가능하지만 크기가 고정적입니다. 연결리스트는 동적 크기 조절이 가능하고 삽입/삭제가 O(1)이지만, 순차 접근만 가능하여 검색이 O(n)입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('정렬 알고리즘 중 퀵소트와 머지소트의 차이점을 설명해주세요.', 2, '퀵소트는 분할정복 방식으로 평균 O(n log n), 최악 O(n²)의 시간복잡도를 가지며 in-place 정렬입니다. 머지소트는 항상 O(n log n)의 안정된 성능을 보이고 stable sort이지만 O(n)의 추가 메모리가 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('해시테이블의 동작 원리와 충돌 해결 방법을 설명해주세요.', 2, '해시테이블은 해시함수를 사용해 키를 배열의 인덱스로 변환하여 O(1) 접근을 제공합니다. 충돌 해결 방법으로는 체이닝(연결리스트 사용)과 개방 주소법(선형 탐사, 이차 탐사, 이중 해싱) 등이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DFS와 BFS의 차이점과 각각의 활용 사례를 설명해주세요.', 2, 'DFS는 스택이나 재귀를 사용해 깊이 우선으로 탐색하며, 경로 찾기나 백트래킹에 적합합니다. BFS는 큐를 사용해 너비 우선으로 탐색하며, 최단 경로 찾기나 레벨별 순회에 적합합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- DevOps 엔지니어 면접 질문들 (질문 세트 4)
('Docker와 가상머신의 차이점을 설명해주세요.', 2, 'Docker는 컨테이너 기술로 호스트 OS의 커널을 공유하여 가볍고 빠른 실행이 가능합니다. 가상머신은 하이퍼바이저 위에 게스트 OS를 설치하여 완전한 격리를 제공하지만 리소스 사용량이 많습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kubernetes의 주요 구성요소와 역할을 설명해주세요.', 2, 'Kubernetes의 주요 구성요소로는 Master Node(API Server, etcd, Scheduler, Controller Manager)와 Worker Node(kubelet, kube-proxy, Container Runtime)가 있으며, Pod, Service, Deployment 등의 오브젝트로 컨테이너를 관리합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CI/CD 파이프라인의 구성 요소와 이점을 설명해주세요.', 2, 'CI/CD는 지속적 통합과 지속적 배포를 의미합니다. 코드 커밋, 빌드, 테스트, 배포가 자동화되어 개발 속도 향상, 오류 조기 발견, 배포 위험 감소, 개발팀 생산성 향상 등의 이점을 제공합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Infrastructure as Code(IaC)의 개념과 장점을 설명해주세요.', 2, 'IaC는 인프라를 코드로 정의하고 관리하는 방법입니다. Terraform, CloudFormation 등을 사용하여 버전 관리, 재사용성, 일관성, 자동화가 가능하며, 인프라 변경의 추적과 롤백이 용이합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('모니터링과 로깅의 중요성과 주요 도구들을 설명해주세요.', 2, '모니터링과 로깅은 시스템 상태 파악, 문제 조기 발견, 성능 최적화, 장애 대응에 필수적입니다. Prometheus, Grafana, ELK Stack, DataDog 등이 주요 도구이며, 메트릭, 로그, 트레이싱을 통합하여 관찰 가능성을 확보합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 데이터베이스 심화 면접 질문들 (질문 세트 5)
('데이터베이스 인덱스의 동작 원리와 종류를 설명해주세요.', 2, '인덱스는 데이터 검색 속도를 향상시키는 자료구조입니다. B-Tree 인덱스가 일반적이며, 클러스터드/논클러스터드, 고유/비고유, 단일/복합 인덱스 등으로 분류됩니다. 검색은 빠르지만 삽입/수정/삭제 시 오버헤드가 발생합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SQL 조인의 종류와 각각의 특징을 설명해주세요.', 2, 'SQL 조인의 종류로는 INNER JOIN(양쪽 테이블에 모두 존재하는 데이터), LEFT/RIGHT JOIN(한쪽 테이블의 모든 데이터), FULL OUTER JOIN(양쪽 테이블의 모든 데이터), CROSS JOIN(카티시안 곱) 등이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('정규화와 역정규화의 개념과 목적을 설명해주세요.', 2, '정규화는 데이터 중복을 제거하고 무결성을 보장하기 위해 테이블을 분해하는 과정입니다. 1NF~5NF까지 있으며, 역정규화는 성능 향상을 위해 의도적으로 중복을 허용하여 조인을 줄이는 기법입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('트랜잭션 격리 수준에 대해 설명해주세요.', 2, '트랜잭션 격리 수준은 동시성 제어를 위한 단계입니다. READ UNCOMMITTED(더티 리드 허용), READ COMMITTED(커밋된 데이터만 읽기), REPEATABLE READ(반복 읽기 보장), SERIALIZABLE(완전 격리)로 나뉘며, 격리 수준이 높을수록 일관성은 높지만 성능은 떨어집니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터베이스 복제(Replication)와 샤딩(Sharding)을 설명해주세요.', 2, '복제는 데이터를 여러 서버에 복사하여 가용성과 읽기 성능을 향상시키는 기법입니다. 샤딩은 대용량 데이터를 여러 데이터베이스에 분산 저장하여 쓰기 성능과 확장성을 향상시키는 기법입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 모바일 앱 개발 면접 질문들 (질문 세트 6)
('Android와 iOS 개발의 차이점을 설명해주세요.', 2, 'Android는 Java/Kotlin으로 개발하며 다양한 기기를 지원하고, iOS는 Swift/Objective-C로 개발하며 Apple 생태계에 최적화되어 있습니다. 각각 다른 아키텍처와 개발 도구를 사용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('React Native와 Flutter의 장단점을 비교해주세요.', 2, 'React Native는 JavaScript 기반으로 빠른 개발이 가능하고 코드 재사용률이 높습니다. Flutter는 Dart 언어 기반으로 높은 성능과 일관된 UI를 제공하며, 구글의 지원을 받고 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('모바일 앱의 메모리 관리 방법을 설명해주세요.', 2, '메모리 누수 방지를 위해 강한 참조 순환을 피하고, 이미지 캐싱을 적절히 사용하며, 백그라운드에서 불필요한 리소스를 해제해야 합니다. 프로파일링 도구로 메모리 사용량을 모니터링합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 웹 보안 전문가 면접 질문들 (질문 세트 7)
('OWASP Top 10 취약점에 대해 설명해주세요.', 2, 'OWASP Top 10은 가장 심각한 웹 애플리케이션 보안 위험을 나열한 것입니다. Injection, Broken Authentication, Sensitive Data Exposure, XXE, Broken Access Control 등이 포함됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SQL Injection 공격과 방어 방법을 설명해주세요.', 2, 'SQL Injection은 사용자 입력을 통해 악의적인 SQL 쿼리를 실행하는 공격입니다. 방어 방법으로는 Prepared Statement 사용, 입력 검증, 최소 권한 원칙 적용 등이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CSRF와 XSS 공격의 차이점과 방어 방법을 설명해주세요.', 2, 'CSRF는 사용자의 권한을 도용하여 의도하지 않은 작업을 수행하는 공격이고, XSS는 악성 스크립트를 삽입하는 공격입니다. CSRF Token, CSP 헤더, 입력 검증 등으로 방어할 수 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 머신러닝 엔지니어 면접 질문들 (질문 세트 8)
('과적합(Overfitting)과 과소적합(Underfitting)을 설명해주세요.', 2, '과적합은 훈련 데이터에만 너무 잘 맞춰진 상태로 일반화 성능이 떨어집니다. 과소적합은 모델이 너무 단순해서 데이터의 패턴을 제대로 학습하지 못한 상태입니다. 정규화, 교차검증 등으로 해결할 수 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('지도학습과 비지도학습의 차이점을 설명해주세요.', 2, '지도학습은 정답이 있는 데이터로 학습하여 예측 모델을 만드는 방법이고, 비지도학습은 정답 없이 데이터의 패턴을 찾는 방법입니다. 분류/회귀 vs 클러스터링/차원축소가 대표적인 예입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gradient Descent 알고리즘의 원리를 설명해주세요.', 2, 'Gradient Descent는 비용 함수의 기울기를 계산하여 최솟값을 찾아가는 최적화 알고리즘입니다. 학습률을 조정하여 수렴 속도와 안정성을 제어하며, Batch/SGD/Mini-batch 방식으로 구현할 수 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 클라우드 아키텍트 면접 질문들 (질문 세트 9)
('AWS의 주요 서비스들을 설명해주세요.', 2, 'EC2(컴퓨팅), S3(스토리지), RDS(데이터베이스), Lambda(서버리스), VPC(네트워킹), IAM(보안) 등이 주요 서비스입니다. 각 서비스는 확장성과 가용성을 제공하며 온디맨드 요금제를 사용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('마이크로서비스 아키텍처의 장단점을 설명해주세요.', 2, '장점: 독립적 배포, 기술 스택 자유도, 장애 격리, 팀 독립성. 단점: 복잡성 증가, 네트워크 지연, 데이터 일관성 문제, 운영 오버헤드. API Gateway, 서비스 메시 등으로 단점을 보완할 수 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('서버리스 아키텍처의 특징과 사용 사례를 설명해주세요.', 2, '서버리스는 서버 관리 없이 코드만 배포하는 아키텍처입니다. 자동 확장, 사용량 기반 과금, 빠른 개발이 장점입니다. 이벤트 처리, API 백엔드, 데이터 변환 등에 적합합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 게임 개발자 면접 질문들 (질문 세트 10)
('Unity와 Unreal Engine의 차이점을 설명해주세요.', 2, 'Unity는 C# 기반으로 2D/3D 모두 지원하며 접근성이 좋습니다. Unreal Engine은 C++ 기반으로 고품질 3D 그래픽에 특화되어 있으며 블루프린트 시스템을 제공합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('게임 성능 최적화 방법을 설명해주세요.', 2, '텍스처 압축, LOD 시스템, 오브젝트 풀링, 컬링 기법, 배치 처리 등을 사용합니다. 프로파일러로 병목 지점을 찾고, GPU/CPU 부하를 분산시키며, 메모리 사용량을 최적화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('게임의 물리 엔진과 충돌 감지를 설명해주세요.', 2, '물리 엔진은 현실적인 물리 법칙을 시뮬레이션합니다. 충돌 감지는 AABB, OBB, Sphere 등의 방법을 사용하며, 쿼터트리나 옥트리로 성능을 최적화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 네트워크 엔지니어 면접 질문들 (질문 세트 11): 질문 51-80
('TCP와 UDP의 차이점과 각각의 활용 사례를 설명해주세요.', 2, 'TCP는 연결 지향적이고 신뢰성 있는 전송을 보장하며 웹 브라우징, 이메일 등에 사용됩니다. UDP는 비연결 지향적이고 빠른 전송이 가능하여 실시간 게임, 동영상 스트리밍 등에 사용됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OSI 7계층 모델의 각 계층과 역할을 설명해주세요.', 2, 'Physical(물리), Data Link(데이터링크), Network(네트워크), Transport(전송), Session(세션), Presentation(표현), Application(응용) 계층으로 구성되며, 각각 하드웨어부터 사용자 인터페이스까지의 역할을 담당합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('라우팅과 스위칭의 차이점을 설명해주세요.', 2, '라우팅은 네트워크 계층에서 패킷의 최적 경로를 결정하고, 스위칭은 데이터링크 계층에서 MAC 주소를 기반으로 프레임을 전달합니다. 라우터는 IP 주소를, 스위치는 MAC 주소를 사용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('VLAN의 개념과 장점을 설명해주세요.', 2, 'VLAN은 물리적으로 같은 네트워크를 논리적으로 분할하는 기술입니다. 브로드캐스트 도메인 분리, 보안 강화, 네트워크 관리 효율성, 대역폭 효율 등의 장점을 제공합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 보안 프로토콜 중 IPSec과 VPN을 설명해주세요.', 2, 'IPSec은 IP 계층에서 데이터 암호화와 인증을 제공하는 프로토콜 집합입니다. VPN은 인터넷을 통해 안전한 가상 사설망을 구축하는 기술로, IPSec, SSL/TLS 등을 사용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DNS 동작 원리와 레코드 타입을 설명해주세요.', 2, 'DNS는 도메인 이름을 IP 주소로 변환하는 분산 시스템입니다. A(IPv4), AAAA(IPv6), CNAME(별칭), MX(메일), NS(네임서버) 등의 레코드 타입이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('로드 밸런싱의 종류와 알고리즘을 설명해주세요.', 2, 'L4(전송 계층), L7(응용 계층) 로드 밸런싱이 있으며, Round Robin, Least Connection, IP Hash, Weighted 등의 알고리즘을 사용하여 트래픽을 분산시킵니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 성능 측정 지표와 모니터링 방법을 설명해주세요.', 2, '대역폭, 지연시간, 패킷 손실률, 처리량을 측정합니다. SNMP, NetFlow, sFlow 등의 프로토콜과 다양한 모니터링 도구를 사용하여 네트워크 상태를 실시간으로 감시합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SDN(Software Defined Network)의 개념을 설명해주세요.', 2, 'SDN은 네트워크 제어 평면과 데이터 평면을 분리하여 중앙에서 네트워크를 프로그래밍 방식으로 제어하는 아키텍처입니다. OpenFlow가 대표적인 프로토콜입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 장애 진단과 문제 해결 과정을 설명해주세요.', 2, '물리적 연결 확인, ping/traceroute 테스트, 로그 분석, 패킷 캡처, 성능 지표 확인을 통해 체계적으로 장애를 진단하고 해결합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('QoS(Quality of Service)의 필요성과 구현 방법을 설명해주세요.', 2, '네트워크 자원이 제한적일 때 중요한 트래픽에 우선순위를 부여하는 기술입니다. 트래픽 분류, 대역폭 할당, 우선순위 큐잉, 트래픽 쉐이핑 등의 방법을 사용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('무선 네트워크(Wi-Fi)의 보안 프로토콜을 설명해주세요.', 2, 'WEP(취약), WPA(개선), WPA2(현재 표준), WPA3(최신) 순으로 발전했습니다. AES 암호화, PSK/Enterprise 인증 방식을 지원하며, 보안성이 지속적으로 강화되고 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('IPv4와 IPv6의 차이점과 전환 방법을 설명해주세요.', 2, 'IPv4는 32비트 주소체계로 주소 고갈 문제가 있고, IPv6는 128비트로 충분한 주소 공간을 제공합니다. 듀얼 스택, 터널링, 번역 기법으로 전환할 수 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 가상화 기술의 종류를 설명해주세요.', 2, 'VLAN, VPN, VXLAN, GRE 터널링 등이 있습니다. 물리적 네트워크 인프라를 논리적으로 분할하여 효율성과 보안성을 향상시킵니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BGP(Border Gateway Protocol)의 역할을 설명해주세요.', 2, 'BGP는 인터넷의 AS(Autonomous System) 간 라우팅 정보를 교환하는 프로토콜입니다. 경로 선택, 정책 적용, 인터넷 전체의 연결성을 담당합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 트래픽 분석과 포렌식 기법을 설명해주세요.', 2, 'Wireshark, tcpdump 등을 사용하여 패킷을 캡처하고 분석합니다. 프로토콜 분석, 성능 문제 진단, 보안 사고 조사에 활용됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('클라우드 네트워킹의 특징과 고려사항을 설명해주세요.', 2, '가상 네트워크, 탄력적 확장, 글로벌 배포가 특징입니다. 지연시간, 대역폭, 보안, 비용 최적화를 고려하여 설계해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 자동화와 프로그래머블 네트워크를 설명해주세요.', 2, 'Ansible, Python, API를 활용하여 네트워크 설정을 자동화합니다. 반복 작업 제거, 일관성 보장, 신속한 배포가 가능합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('멀티캐스트와 브로드캐스트의 차이점을 설명해주세요.', 2, '브로드캐스트는 네트워크의 모든 호스트에게 전송하고, 멀티캐스트는 특정 그룹의 호스트들에게만 전송합니다. 네트워크 효율성 면에서 멀티캐스트가 우수합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 용량 계획과 확장 전략을 설명해주세요.', 2, '현재 사용량 분석, 성장률 예측, 피크 트래픽 고려, 여유분 확보를 통해 용량을 계획합니다. 단계적 확장과 탄력적 확장 전략을 수립합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MPLS(Multi-Protocol Label Switching)의 장점을 설명해주세요.', 2, 'MPLS는 레이블 기반 포워딩으로 높은 성능과 QoS를 제공합니다. VPN 서비스, 트래픽 엔지니어링, 빠른 장애 복구가 가능합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 보안 아키텍처와 방어 전략을 설명해주세요.', 2, '다층 방어, DMZ 구성, 접근 제어, 침입 탐지/방지, 암호화를 통한 종합적인 보안 체계를 구축합니다. 제로 트러스트 모델도 고려해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('5G 네트워크의 특징과 기술적 개선점을 설명해주세요.', 2, '높은 속도, 낮은 지연시간, 대규모 연결을 지원합니다. 네트워크 슬라이싱, 엣지 컴퓨팅, mmWave 기술 등이 핵심 기술입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 디바이스 관리와 펌웨어 업데이트 전략을 설명해주세요.', 2, 'SNMP, SSH, 웹 인터페이스를 통한 원격 관리, 정기적인 보안 패치, 펌웨어 버전 관리, 백업/복구 절차를 체계화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 컨버전스 시간과 최적화 방법을 설명해주세요.', 2, '라우팅 프로토콜이 네트워크 변화에 적응하는 시간입니다. 빠른 컨버전스를 위해 적절한 타이머 설정, BFD(Bidirectional Forwarding Detection) 사용 등을 적용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- QA 테스트 엔지니어 면접 질문들 (질문 세트 12): 질문 81-110
('단위 테스트, 통합 테스트, 시스템 테스트의 차이점을 설명해주세요.', 2, '단위 테스트는 개별 모듈 검증, 통합 테스트는 모듈 간 연동 검증, 시스템 테스트는 전체 시스템의 요구사항 만족 여부를 검증합니다. 각각 다른 범위와 목적을 가집니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 자동화의 장점과 도구들을 설명해주세요.', 2, '반복 작업 감소, 일관된 테스트 실행, 빠른 피드백, 회귀 테스트 효율성 등이 장점입니다. Selenium, Cypress, Jest, JUnit, Postman 등이 대표적인 자동화 도구입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('성능 테스트의 종류와 각각의 목적을 설명해주세요.', 2, '부하 테스트(정상 부하), 스트레스 테스트(한계점 확인), 볼륨 테스트(대용량 데이터), 스파이크 테스트(급격한 부하 증가) 등이 있으며, 각각 다른 성능 측면을 검증합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 케이스 설계 기법을 설명해주세요.', 2, '동등 분할, 경계값 분석, 결정 테이블, 상태 전이 테스트, 유스케이스 테스트 등이 있습니다. 각 기법은 입력값의 특성과 시스템의 동작에 따라 선택적으로 적용됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 주도 개발(TDD)의 개념과 장점을 설명해주세요.', 2, 'TDD는 Red-Green-Refactor 사이클로 테스트를 먼저 작성하고 코드를 구현하는 방법론입니다. 코드 품질 향상, 버그 감소, 설계 개선, 문서화 효과 등의 장점이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('API 테스트 전략과 도구를 설명해주세요.', 2, 'REST API, GraphQL API의 기능, 성능, 보안을 테스트합니다. Postman, REST Assured, Newman, JMeter 등을 사용하여 자동화된 API 테스트를 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('모바일 앱 테스트의 특수성과 고려사항을 설명해주세요.', 2, '다양한 디바이스, OS 버전, 화면 크기, 네트워크 상태를 고려해야 합니다. 배터리 소모, 메모리 사용량, 터치 제스처, 센서 기능 등도 테스트 범위에 포함됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('보안 테스트의 주요 영역과 방법론을 설명해주세요.', 2, '인증, 인가, 데이터 보호, 세션 관리, 입력 검증을 테스트합니다. OWASP 가이드라인, 침투 테스트, 정적/동적 분석 도구를 활용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 데이터 관리 전략을 설명해주세요.', 2, '테스트 환경별 데이터 분리, 마스킹/익명화, 데이터 생성 자동화, 일관성 유지를 고려합니다. 개인정보 보호와 현실적인 테스트 시나리오 구현의 균형이 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('크로스 브라우저 테스트의 필요성과 방법을 설명해주세요.', 2, '다양한 브라우저에서 일관된 사용자 경험을 보장하기 위해 필요합니다. BrowserStack, Sauce Labs, Selenium Grid 등을 활용하여 효율적으로 수행할 수 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 환경 구성과 관리 방법을 설명해주세요.', 2, '개발, 테스트, 스테이징, 프로덕션 환경을 분리하고, Docker, Kubernetes를 활용한 컨테이너화, Infrastructure as Code로 일관성을 유지합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('결함 관리 프로세스와 우선순위 결정 기준을 설명해주세요.', 2, '발견, 분류, 할당, 수정, 재테스트, 종료의 생명주기를 거칩니다. 심각도(Critical/High/Medium/Low)와 우선순위를 비즈니스 영향도에 따라 결정합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 커버리지의 종류와 측정 방법을 설명해주세요.', 2, '코드 커버리지(라인, 브랜치, 조건), 기능 커버리지, 요구사항 커버리지 등이 있습니다. 도구를 통한 자동 측정과 정기적인 모니터링이 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('접근성 테스트의 중요성과 방법을 설명해주세요.', 2, '장애인, 고령자 등 모든 사용자가 접근할 수 있도록 보장합니다. WCAG 가이드라인 준수, 스크린 리더 테스트, 키보드 탐색, 색상 대비 등을 검증합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 메트릭과 리포팅 전략을 설명해주세요.', 2, '테스트 실행률, 통과율, 결함 밀도, 커버리지 등을 측정합니다. 이해관계자별 맞춤형 리포트 제공과 트렌드 분석을 통한 품질 개선 방향을 제시합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CI/CD 파이프라인에서의 테스트 통합 방법을 설명해주세요.', 2, '코드 커밋 시 자동 테스트 실행, 품질 게이트 설정, 병렬 테스트 실행, 빠른 피드백 제공을 구현합니다. Jenkins, GitLab CI, GitHub Actions 등을 활용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('마이크로서비스 아키텍처에서의 테스트 전략을 설명해주세요.', 2, '서비스별 독립적 테스트, 계약 테스트(Contract Testing), 서비스 간 통합 테스트, 엔드투엔드 테스트의 균형을 맞춰야 합니다. Test Pyramid 개념을 적용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('게임 테스트의 특수성과 고려사항을 설명해주세요.', 2, '게임플레이, 밸런스, 그래픽 성능, 멀티플레이어 동기화, 플랫폼별 특성을 테스트해야 합니다. 사용자 경험과 재미 요소도 중요한 테스트 대상입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('클라우드 환경에서의 테스트 전략을 설명해주세요.', 2, '탄력적 확장, 지역별 배포, 장애 조치, 비용 최적화를 고려합니다. AWS, Azure, GCP의 테스트 서비스와 DevOps 도구를 활용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AI/ML 시스템 테스트의 도전과제와 접근법을 설명해주세요.', 2, '모델 성능, 편향성, 데이터 품질, 모델 드리프트를 테스트해야 합니다. A/B 테스트, 카나리 배포, 지속적인 모니터링이 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 자동화 프레임워크 설계 원칙을 설명해주세요.', 2, '모듈화, 재사용성, 유지보수성, 확장성을 고려합니다. Page Object Model, 데이터 분리, 설정 관리, 리포팅 기능을 체계적으로 구현합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('사용자 수용 테스트(UAT) 계획과 실행 방법을 설명해주세요.', 2, '실제 사용자 또는 대표 사용자가 비즈니스 요구사항 충족 여부를 검증합니다. 테스트 시나리오 작성, 환경 준비, 교육, 피드백 수집 과정이 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('로드 테스트와 스트레스 테스트 시나리오 설계를 설명해주세요.', 2, '실제 사용 패턴 분석, 점진적 부하 증가, 동시 사용자 수 산정, 시스템 리소스 모니터링을 통해 성능 한계와 병목 지점을 파악합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 실행 최적화와 효율성 향상 방법을 설명해주세요.', 2, '병렬 실행, 스마트 테스트 선택, 결함 예측, 테스트 환경 최적화를 통해 실행 시간을 단축하고 리소스 효율성을 높입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 팀과 개발팀의 협업 방법을 설명해주세요.', 2, '조기 개입(Shift-Left), 공동 요구사항 분석, 페어 테스팅, 지식 공유, 통합된 도구 사용을 통해 효과적인 협업 체계를 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 프로세스 개선과 성숙도 평가를 설명해주세요.', 2, 'TMMi(Test Maturity Model integration) 등의 프레임워크를 활용하여 현재 수준을 평가하고, 단계적 개선 계획을 수립합니다. 지속적인 프로세스 개선이 핵심입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 아키텍처와 도구 통합 전략을 설명해주세요.', 2, '테스트 도구 간 연동, 데이터 흐름 설계, 표준화, 중앙집중식 관리를 통해 일관되고 효율적인 테스트 생태계를 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('위험 기반 테스트 접근법을 설명해주세요.', 2, '비즈니스 영향도와 장애 발생 가능성을 분석하여 테스트 우선순위를 결정합니다. 제한된 시간과 자원으로 최대 효과를 얻을 수 있는 전략입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 문서화와 지식 관리 방법을 설명해주세요.', 2, '테스트 계획, 케이스, 절차, 결과를 체계적으로 문서화하고, 위키, 형상관리, 지식베이스를 통해 팀 지식을 공유하고 보존합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('글로벌 서비스의 다국가 테스트 전략을 설명해주세요.', 2, '언어, 문화, 법규, 시간대, 통화 등을 고려한 현지화 테스트가 필요합니다. 각국의 특성에 맞는 테스트 시나리오와 환경을 구성해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- UI/UX 디자이너 면접 질문들 추가 (질문 세트 13): 질문 187-216 (25개 추가)
('UI와 UX의 차이점을 설명해주세요.', 2, 'UI(User Interface)는 사용자가 직접 보고 상호작용하는 시각적 요소입니다. UX(User Experience)는 사용자가 제품을 사용하면서 느끼는 전반적인 경험과 만족도를 의미합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('사용자 페르소나(Persona) 작성의 목적과 방법을 설명해주세요.', 2, '타겟 사용자를 구체적으로 정의하여 디자인 결정의 기준점을 제공합니다. 사용자 조사 데이터를 바탕으로 인구통계, 행동 패턴, 목표, 불만사항 등을 포함한 가상의 사용자 프로필을 작성합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('와이어프레임과 프로토타입의 차이를 설명해주세요.', 2, '와이어프레임은 페이지의 구조와 레이아웃을 보여주는 저해상도 설계도입니다. 프로토타입은 실제 제품과 유사한 상호작용이 가능한 모형으로, 사용자 테스트와 검증에 활용됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('접근성(Accessibility) 디자인 원칙을 설명해주세요.', 2, 'WCAG 가이드라인을 따라 인지가능성, 운용가능성, 이해가능성, 견고성을 보장해야 합니다. 색상 대비, 키보드 탐색, 스크린 리더 지원, 대체 텍스트 제공 등이 포함됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('반응형 웹 디자인의 핵심 개념을 설명해주세요.', 2, '다양한 디바이스와 화면 크기에 적응하는 디자인 방법론입니다. 유연한 그리드, 미디어 쿼리, 플렉서블 이미지를 사용하여 최적의 사용자 경험을 제공합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('디자인 시스템의 구성 요소와 장점을 설명해주세요.', 2, '색상, 타이포그래피, 컴포넌트, 아이콘, 레이아웃 가이드라인으로 구성됩니다. 일관성 유지, 효율성 증대, 브랜드 아이덴티티 강화, 협업 개선 등의 장점이 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('사용자 중심 설계(UCD) 프로세스를 설명해주세요.', 2, '사용자 조사, 요구사항 분석, 디자인, 프로토타이핑, 사용자 테스트, 반복 개선의 순환 과정입니다. 각 단계에서 사용자의 피드백을 반영하여 사용성을 향상시킵니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('정보 아키텍처(IA)의 중요성과 구성 방법을 설명해주세요.', 2, '콘텐츠를 논리적으로 구조화하여 사용자가 쉽게 탐색할 수 있도록 합니다. 카드 소팅, 사이트 맵 작성, 네비게이션 설계, 라벨링 시스템 구축이 포함됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('사용성 테스트의 종류와 방법론을 설명해주세요.', 2, '조절된 테스트, 비조절된 테스트, 원격 테스트, A/B 테스트 등이 있습니다. 태스크 기반 테스트, 싱크 앨라우드 프로토콜, 정량적/정성적 데이터 수집이 핵심입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('색채 이론과 UI 디자인에서의 활용을 설명해주세요.', 2, '색상환, 보색, 유사색, 3색 조화 등의 이론을 활용합니다. 브랜드 아이덴티티, 사용자 감정, 가독성, 접근성을 고려하여 색상 팔레트를 구성합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('타이포그래피의 기본 원칙을 설명해주세요.', 2, '가독성, 계층 구조, 일관성이 핵심입니다. 폰트 크기, 줄 간격, 자간, 여백을 적절히 조정하여 읽기 쉽고 아름다운 텍스트를 구성합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('모바일 퍼스트 디자인 접근법을 설명해주세요.', 2, '작은 화면부터 디자인을 시작하여 점진적으로 큰 화면으로 확장하는 방법입니다. 핵심 기능에 집중하고, 터치 인터페이스를 우선 고려합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('마이크로 인터랙션의 역할과 설계 원칙을 설명해주세요.', 2, '사용자의 행동에 대한 즉각적인 피드백을 제공하는 작은 애니메이션입니다. 기능적 목적, 적절한 타이밍, 자연스러운 움직임이 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('디자인 트렌드와 사용성의 균형을 맞추는 방법을 설명해주세요.', 2, '최신 트렌드를 파악하되, 사용자의 편의성과 접근성을 우선시해야 합니다. 데이터 기반 의사결정과 지속적인 사용자 테스트로 검증합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('스케치와 Figma 같은 디자인 도구의 활용법을 설명해주세요.', 2, '컴포넌트 라이브러리 구축, 심볼 활용, 플러그인 사용, 버전 관리, 협업 기능을 효과적으로 활용하여 효율적인 디자인 워크플로우를 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('사용자 여정 맵(User Journey Map) 작성 방법을 설명해주세요.', 2, '사용자의 전체 경험 과정을 시각화하여 터치포인트, 감정 변화, 페인 포인트를 파악합니다. 단계별 사용자 행동, 생각, 감정을 매핑합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('콘텐츠 우선 디자인 접근법을 설명해주세요.', 2, '실제 콘텐츠를 먼저 준비하고 이를 바탕으로 디자인을 구성하는 방법입니다. 의미 있는 디자인 결정과 현실적인 레이아웃을 가능하게 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('브랜드 아이덴티티와 UI 디자인의 연계를 설명해주세요.', 2, '브랜드의 가치와 성격을 시각적으로 표현하여 일관된 사용자 경험을 제공합니다. 로고, 색상, 톤앤매너, 이미지 스타일을 통합적으로 적용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('그리드 시스템의 원리와 활용법을 설명해주세요.', 2, '콘텐츠를 체계적으로 배치하는 기준선 시스템입니다. 일관성 있는 레이아웃, 시각적 계층 구조, 반응형 디자인의 기초가 됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('에러 상태와 엠프티 스테이트 디자인을 설명해주세요.', 2, '시스템 오류나 콘텐츠 부재 시 사용자에게 명확한 안내를 제공합니다. 문제 상황 설명, 해결 방안 제시, 대안 행동 유도가 포함되어야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('디자인 검토와 피드백 프로세스를 설명해주세요.', 2, '체계적인 검토 기준, 명확한 피드백 방식, 개선 사항 우선순위 설정이 필요합니다. 디자인 시스템 준수, 사용성, 브랜드 일관성을 점검합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('다크 모드 디자인 고려사항을 설명해주세요.', 2, '색상 대비 조정, 가독성 확보, 에너지 효율성을 고려합니다. 단순한 색상 반전이 아닌 전용 색상 팔레트와 컴포넌트 최적화가 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('국제화(i18n) 디자인 전략을 설명해주세요.', 2, '다양한 언어와 문화권을 고려한 유연한 디자인 시스템 구축이 필요합니다. 텍스트 길이 변화, 읽기 방향, 문화적 색상 인식을 고려합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('성능과 사용성을 고려한 이미지 최적화를 설명해주세요.', 2, '적절한 파일 형식 선택, 압축, 반응형 이미지, 지연 로딩을 활용합니다. 사용자 경험을 해치지 않으면서 로딩 성능을 개선합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('디자인 핸드오프 프로세스와 개발 협업을 설명해주세요.', 2, '명확한 스펙 문서, 에셋 제공, 인터랙션 가이드, 개발자와의 소통 채널 구축이 필요합니다. Figma Dev Mode, Zeplin 등의 도구를 활용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- IT 프로젝트 매니저 면접 질문들 추가 (질문 세트 14): 질문 217-246 (25개 추가)  
('애자일과 폭포수 모델의 차이점을 설명해주세요.', 2, '애자일은 반복적이고 점진적인 개발 방식으로 변화에 빠르게 대응합니다. 폭포수는 순차적이고 계획 중심적 접근으로 안정성과 예측 가능성을 중시합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('스크럼 프레임워크의 핵심 구성요소를 설명해주세요.', 2, '스크럼 마스터, 제품 오너, 개발팀의 역할과 스프린트, 데일리 스크럼, 스프린트 리뷰, 회고의 이벤트, 제품 백로그와 스프린트 백로그의 아티팩트로 구성됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 위험 관리 프로세스를 설명해주세요.', 2, '위험 식별, 분석, 평가, 대응 계획 수립, 모니터링의 단계로 진행됩니다. 확률과 영향도를 기준으로 우선순위를 정하고 예방/완화/전가/수용 전략을 적용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('이해관계자 관리 방법을 설명해주세요.', 2, '이해관계자를 식별하고 영향력과 관심도에 따라 분류합니다. 각 그룹별 맞춤형 커뮤니케이션 계획을 수립하고 지속적으로 참여를 유도합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 범위 관리의 중요성을 설명해주세요.', 2, '명확한 범위 정의, WBS 작성, 변경 통제 프로세스를 통해 범위 크리프를 방지합니다. 요구사항 추적과 승인된 변경사항만 반영하는 것이 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 일정 관리 기법을 설명해주세요.', 2, 'CPM(임계경로법), PERT, 간트 차트를 활용하여 일정을 계획하고 관리합니다. 버퍼 시간 확보, 의존성 관리, 진행률 모니터링이 핵심입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('예산 관리와 비용 통제 방법을 설명해주세요.', 2, '비용 추정, 예산 수립, 비용 통제, EVM(Earned Value Management)를 통한 성과 측정이 포함됩니다. CPI, SPI 지표로 프로젝트 건전성을 평가합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('품질 관리 계획 수립 방법을 설명해주세요.', 2, '품질 기준 정의, QA/QC 활동 계획, 검토 및 승인 프로세스, 결함 관리 절차를 포함합니다. 지속적인 개선과 교훈 학습이 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('팀 빌딩과 동기부여 방법을 설명해주세요.', 2, '팀원의 강점 파악, 역할 명확화, 목표 공유, 성취 인정, 성장 기회 제공을 통해 팀의 응집력과 성과를 향상시킵니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('커뮤니케이션 계획 수립 방법을 설명해주세요.', 2, '이해관계자별 정보 요구사항 파악, 커뮤니케이션 채널 선정, 빈도와 형식 결정, 피드백 수집 방법을 체계적으로 계획합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('변경 관리 프로세스를 설명해주세요.', 2, '변경 요청 접수, 영향도 분석, 승인/거부 결정, 구현, 검증의 단계로 진행됩니다. CCB(Change Control Board)를 통한 체계적 관리가 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 성과 측정 지표를 설명해주세요.', 2, 'KPI, OKR, 대시보드를 활용하여 진행률, 품질, 비용, 일정 성과를 측정합니다. 정량적/정성적 지표의 균형있는 활용이 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('분산 팀 관리 방법을 설명해주세요.', 2, '시간대 고려, 온라인 협업 도구 활용, 문화적 차이 인식, 명확한 커뮤니케이션, 정기적 화상회의를 통해 효과적인 원격 협업을 구현합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 종료와 교훈 학습을 설명해주세요.', 2, '최종 산출물 인수, 계약 종료, 자원 해제, 문서 정리, 회고와 교훈 학습을 통해 프로젝트를 완료하고 조직 역량을 축적합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('멀티 프로젝트 관리 전략을 설명해주세요.', 2, '프로젝트 간 우선순위 설정, 자원 할당 최적화, 의존성 관리, 포트폴리오 관점에서의 통합 관리가 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('디지털 전환 프로젝트 특성을 설명해주세요.', 2, '기술적 복잡성, 조직 문화 변화, 사용자 수용성, 데이터 마이그레이션, 레거시 시스템 통합 등의 도전과제를 체계적으로 관리해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 거버넌스 체계를 설명해주세요.', 2, '의사결정 구조, 역할과 책임, 프로세스 표준, 리포팅 체계를 명확히 정의하여 프로젝트의 투명성과 책임성을 확보합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('조달 관리 프로세스를 설명해주세요.', 2, '조달 계획, 입찰 관리, 계약 체결, 성과 모니터링, 계약 종료의 과정을 거칩니다. 공급업체 선정과 관계 관리가 핵심입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 문서 관리 방법을 설명해주세요.', 2, '문서 분류 체계, 버전 관리, 접근 권한, 업데이트 절차, 보존 정책을 수립하여 프로젝트 지식을 효과적으로 관리합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('갈등 관리와 해결 방법을 설명해주세요.', 2, '갈등의 원인 파악, 이해관계자 입장 이해, 협상과 조정, 대안 제시를 통해 건설적인 해결책을 도출합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 자동화 도구 활용을 설명해주세요.', 2, 'JIRA, Asana, MS Project, Slack 등의 도구를 활용하여 일정 관리, 작업 추적, 협업, 리포팅을 자동화하고 효율성을 향상시킵니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('리스크 기반 테스팅 전략을 설명해주세요.', 2, '비즈니스 영향도가 높은 영역에 테스트 자원을 집중 배치하여 효율적인 품질 보증을 달성합니다. 리스크 매트릭스를 활용한 우선순위 결정이 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터 마이그레이션 프로젝트 관리를 설명해주세요.', 2, '데이터 품질 검증, 매핑 규칙 정의, 단계별 이관, 검증 테스트, 롤백 계획을 포함한 체계적인 접근이 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('프로젝트 포트폴리오 관리를 설명해주세요.', 2, '전략적 목표에 따른 프로젝트 선정, 자원 할당 최적화, 성과 모니터링, 포트폴리오 밸런싱을 통해 조직 가치를 극대화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('하이브리드 방법론 적용을 설명해주세요.', 2, '프로젝트 특성에 따라 애자일과 전통적 방법론을 조합하여 적용합니다. 계획이 중요한 부분은 전통적 방식을, 변화가 빈번한 부분은 애자일 방식을 사용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 시스템 관리자 면접 질문들 추가 (질문 세트 15): 질문 247-276 (25개 추가)
('Linux 시스템의 부팅 과정을 설명해주세요.', 2, 'BIOS/UEFI → 부트로더(GRUB) → 커널 로딩 → initrd/initramfs → systemd/init → 런레벨/타겟 → 사용자 로그인의 순서로 진행됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 로그 관리와 분석 방법을 설명해주세요.', 2, 'rsyslog, journald를 통한 로그 수집, logrotate으로 용량 관리, ELK 스택으로 중앙집중식 분석, 정기적인 로그 검토와 알림 설정이 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 성능 모니터링 도구들을 설명해주세요.', 2, 'top, htop, iotop, netstat, ss, sar, vmstat 등의 명령어와 Nagios, Zabbix, Prometheus 등의 모니터링 솔루션을 활용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('백업 및 복구 전략을 설명해주세요.', 2, '전체/증분/차등 백업 방식, 3-2-1 백업 규칙(3개 사본, 2개 매체, 1개 오프사이트), RTO/RPO 목표 설정, 정기적인 복구 테스트가 핵심입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 설정과 문제 해결을 설명해주세요.', 2, 'ifconfig/ip 명령어, 라우팅 테이블 관리, 방화벽 설정, DNS 구성, 네트워크 진단 도구(ping, traceroute, nslookup)를 활용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('사용자 및 권한 관리 방법을 설명해주세요.', 2, '계정 생성/삭제, 그룹 관리, sudo 권한 설정, 파일 권한(chmod, chown), ACL(Access Control List) 활용을 통한 보안 관리가 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('패키지 관리 시스템을 설명해주세요.', 2, 'yum/dnf(Red Hat), apt(Debian/Ubuntu), zypper(SUSE) 등의 패키지 매니저를 사용하여 소프트웨어 설치, 업데이트, 의존성 관리를 수행합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 보안 강화 방법을 설명해주세요.', 2, '불필요한 서비스 비활성화, 방화벽 설정, SELinux/AppArmor 활용, 정기적인 보안 패치, 시스템 감사 로그 모니터링이 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('스토리지 관리와 파일시스템을 설명해주세요.', 2, 'LVM을 통한 논리 볼륨 관리, RAID 구성, ext4/XFS 파일시스템 선택, 마운트 관리, 디스크 사용량 모니터링이 포함됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 자동화와 스크립팅을 설명해주세요.', 2, 'Bash/Python 스크립트, cron 작업 스케줄링, Ansible/Puppet/Chef을 활용한 설정 관리 자동화로 운영 효율성을 향상시킵니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('가상화 기술과 컨테이너 관리를 설명해주세요.', 2, 'VMware, KVM, Xen 하이퍼바이저와 Docker, Podman 컨테이너 기술을 활용하여 자원 효율성과 격리성을 확보합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('웹 서버 설정과 관리를 설명해주세요.', 2, 'Apache HTTP Server, Nginx 설정, 가상 호스트 구성, SSL/TLS 인증서 관리, 성능 튜닝, 로그 분석이 포함됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터베이스 서버 관리를 설명해주세요.', 2, 'MySQL/PostgreSQL 설치 및 구성, 백업/복구, 사용자 권한 관리, 성능 모니터링, 쿼리 최적화, 고가용성 구성이 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 장애 대응 절차를 설명해주세요.', 2, '장애 감지, 영향도 평가, 임시 조치, 근본 원인 분석, 영구 해결책 적용, 사후 검토의 단계적 접근이 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('고가용성 시스템 구성을 설명해주세요.', 2, '클러스터링, 로드 밸런싱, 페일오버 메커니즘, 데이터 복제를 통해 시스템 가용성을 향상시키고 단일 장애점을 제거합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 용량 계획 방법을 설명해주세요.', 2, '현재 사용률 분석, 성장률 예측, 피크 부하 고려, 하드웨어 확장 계획을 통해 적절한 시스템 용량을 확보합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 보안 구성을 설명해주세요.', 2, 'iptables/firewalld, VPN 설정, IDS/IPS 구축, 네트워크 분할, 접근 제어 목록(ACL)을 통한 보안 강화가 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 문서화와 절차 관리를 설명해주세요.', 2, '시스템 구성도, 운영 매뉴얼, 장애 대응 가이드, 변경 관리 절차를 체계적으로 문서화하고 최신 상태로 유지합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('클라우드 마이그레이션 전략을 설명해주세요.', 2, '현재 환경 분석, 클라우드 아키텍처 설계, 단계적 이전 계획, 성능 검증, 비용 최적화를 통한 체계적인 마이그레이션을 수행합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 업데이트와 패치 관리를 설명해주세요.', 2, '보안 패치 우선순위 결정, 테스트 환경 검증, 배포 일정 계획, 롤백 준비, 변경 사항 추적을 통한 안전한 업데이트를 진행합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('로그 중앙화와 SIEM 구축을 설명해주세요.', 2, '로그 수집, 정규화, 상관관계 분석, 위협 탐지, 대응 자동화를 통해 보안 이벤트를 통합 관리합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('인프라스트럭처 코드화(IaC)를 설명해주세요.', 2, 'Terraform, Ansible을 활용하여 인프라를 코드로 관리하고, 버전 관리, 자동화 배포, 일관성 보장을 실현합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('성능 튜닝 방법론을 설명해주세요.', 2, '병목 지점 식별, 시스템 자원 분석, 커널 파라미터 조정, 애플리케이션 최적화를 통해 시스템 성능을 향상시킵니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('재해 복구 계획을 설명해주세요.', 2, 'BIA(비즈니스 영향 분석), DR 사이트 구축, 복구 절차 수립, 정기적인 DR 훈련을 통해 재해 상황에 대비합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('시스템 간 연동과 API 관리를 설명해주세요.', 2, '인터페이스 설계, 데이터 포맷 표준화, 에러 핸들링, API 게이트웨이 구성을 통한 안정적인 시스템 연동을 구현합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 신입 개발자 기초 면접 질문들 추가 (질문 세트 16): 질문 277-306 (25개 추가)
('객체지향 프로그래밍의 4가지 특성을 설명해주세요.', 2, '캡슐화(데이터와 메서드를 하나로 묶음), 상속(기존 클래스를 확장), 다형성(같은 인터페이스로 다른 구현), 추상화(복잡한 내부를 숨기고 간단한 인터페이스 제공)입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('변수와 상수의 차이점을 설명해주세요.', 2, '변수는 프로그램 실행 중에 값을 변경할 수 있는 메모리 공간이고, 상수는 한 번 값이 정해지면 변경할 수 없는 메모리 공간입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('스택과 힙 메모리의 차이점을 설명해주세요.', 2, '스택은 지역변수와 함수 호출 정보를 저장하는 LIFO 구조의 빠른 메모리입니다. 힙은 동적으로 할당되는 객체들을 저장하는 자유로운 메모리 공간입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('컴파일러와 인터프리터의 차이점을 설명해주세요.', 2, '컴파일러는 소스코드를 기계어로 미리 변환하여 실행 속도가 빠르고, 인터프리터는 실행 시점에 코드를 해석하여 유연성이 높지만 상대적으로 느립니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('함수와 메서드의 차이점을 설명해주세요.', 2, '함수는 독립적으로 존재하는 코드 블록이고, 메서드는 클래스 내부에 정의되어 객체와 연관된 함수입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('배열과 리스트의 차이점을 설명해주세요.', 2, '배열은 고정된 크기의 동일한 타입 요소들을 메모리에 연속적으로 저장합니다. 리스트는 동적 크기이며 서로 다른 타입의 요소들을 포함할 수 있습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('조건문과 반복문의 종류를 설명해주세요.', 2, '조건문에는 if-else, switch-case가 있고, 반복문에는 for, while, do-while이 있습니다. 각각 다른 상황에 적합한 특성을 가집니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('예외 처리의 중요성과 방법을 설명해주세요.', 2, '예상치 못한 오류 상황에 대비하여 프로그램의 안정성을 보장합니다. try-catch-finally 블록을 사용하여 예외를 처리하고 적절한 메시지를 제공합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('재귀함수의 개념과 주의사항을 설명해주세요.', 2, '함수가 자기 자신을 호출하는 방식으로, 기저 조건과 재귀 조건이 명확해야 합니다. 스택 오버플로우를 방지하기 위해 종료 조건을 반드시 설정해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터 타입과 형변환을 설명해주세요.', 2, '기본형(int, float, boolean, char)과 참조형(객체, 배열)으로 구분됩니다. 명시적/암시적 형변환이 있으며, 데이터 손실을 주의해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('포인터와 참조의 개념을 설명해주세요.', 2, '포인터는 메모리 주소를 저장하는 변수이고, 참조는 기존 변수의 별명입니다. 메모리 관리와 효율적인 데이터 접근에 중요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('문자열 처리 방법을 설명해주세요.', 2, '문자열 생성, 연결, 분할, 검색, 치환 등의 기본 연산과 정규표현식을 활용한 패턴 매칭, 인코딩 처리를 포함합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('파일 입출력 처리 방법을 설명해주세요.', 2, '파일 열기, 읽기, 쓰기, 닫기의 기본 과정과 스트림, 버퍼링, 예외 처리, 자원 해제를 고려한 안전한 파일 처리가 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('알고리즘 복잡도 분석 방법을 설명해주세요.', 2, '시간 복잡도와 공간 복잡도를 Big O 표기법으로 분석합니다. 최선, 평균, 최악의 경우를 고려하여 알고리즘의 효율성을 평가합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('정렬 알고리즘의 기본 개념을 설명해주세요.', 2, '버블 정렬, 선택 정렬, 삽입 정렬 등의 기본 정렬과 퀵 정렬, 머지 정렬 등의 고급 정렬 알고리즘의 원리와 시간복잡도를 이해해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('검색 알고리즘의 종류를 설명해주세요.', 2, '선형 검색은 O(n)으로 간단하지만 느리고, 이진 검색은 O(log n)으로 빠르지만 정렬된 데이터가 필요합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('자료구조의 기본 개념을 설명해주세요.', 2, '데이터를 효율적으로 저장하고 접근하기 위한 구조입니다. 배열, 연결리스트, 스택, 큐, 트리, 그래프 등이 대표적입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터베이스 기본 개념을 설명해주세요.', 2, '구조화된 데이터를 저장, 관리, 검색하는 시스템입니다. 테이블, 레코드, 필드, 기본키, 외래키 등의 기본 용어를 이해해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SQL 기본 문법을 설명해주세요.', 2, 'SELECT(조회), INSERT(삽입), UPDATE(수정), DELETE(삭제)의 기본 CRUD 연산과 WHERE, ORDER BY, GROUP BY 절을 활용한 데이터 조작을 포함합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('네트워크 기본 개념을 설명해주세요.', 2, 'IP 주소, 포트, 프로토콜(HTTP, TCP, UDP), 클라이언트-서버 모델 등의 기본 개념을 이해하고 네트워크 통신의 원리를 파악해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('웹 개발 기초를 설명해주세요.', 2, 'HTML(구조), CSS(스타일), JavaScript(동작)의 역할과 브라우저의 동작 원리, HTTP 요청/응답 과정을 이해해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('버전 관리 시스템의 중요성을 설명해주세요.', 2, 'Git을 활용하여 코드 변경 이력 관리, 협업, 브랜치 관리, 병합 등을 수행합니다. 커밋 메시지 작성법과 기본 명령어를 숙지해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('디버깅 기법을 설명해주세요.', 2, '브레이크포인트 설정, 변수 값 확인, 스택 추적, 로그 활용 등을 통해 오류를 체계적으로 찾고 해결합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('코드 품질 향상 방법을 설명해주세요.', 2, '명확한 변수명 사용, 함수 분리, 주석 작성, 코드 리뷰, 리팩토링을 통해 읽기 쉽고 유지보수 가능한 코드를 작성합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트의 중요성과 종류를 설명해주세요.', 2, '단위 테스트, 통합 테스트, 시스템 테스트를 통해 코드의 정확성을 검증하고 버그를 조기에 발견합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 경력 개발자 심화 면접 질문들 추가 (질문 세트 17): 질문 307-336 (25개 추가)
('시스템 아키텍처 설계 원칙을 설명해주세요.', 2, '확장성, 가용성, 성능, 보안, 유지보수성을 고려한 설계가 필요합니다. SOLID 원칙, 관심사의 분리, 느슨한 결합을 통해 견고한 아키텍처를 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('대용량 트래픽 처리 전략을 설명해주세요.', 2, '로드 밸런싱, 캐싱, CDN, 데이터베이스 샤딩, 비동기 처리, 마이크로서비스 아키텍처를 통해 확장성 있는 시스템을 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('코드 리뷰 문화 정착 방법을 설명해주세요.', 2, '명확한 가이드라인 수립, 건설적인 피드백, 지식 공유, 팀 학습 문화 조성을 통해 코드 품질 향상과 팀 역량 강화를 동시에 달성합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('기술 부채 관리 전략을 설명해주세요.', 2, '기술 부채를 식별하고 우선순위를 정하여 계획적으로 해결합니다. 리팩토링, 문서화, 테스트 코드 작성을 통해 장기적인 코드 건전성을 유지합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('팀 리더십과 멘토링 방법을 설명해주세요.', 2, '팀원의 성장 지원, 명확한 목표 설정, 효과적인 커뮤니케이션, 갈등 해결, 동기부여를 통해 고성과 팀을 구축하고 이끕니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('레거시 시스템 현대화 전략을 설명해주세요.', 2, '점진적 마이그레이션, Strangler Fig 패턴, API 래핑, 데이터 마이그레이션, 기능 검증을 통해 비즈니스 연속성을 보장하면서 시스템을 현대화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DevOps 문화 구축 방법을 설명해주세요.', 2, '개발과 운영의 협업 강화, CI/CD 파이프라인 구축, 자동화, 모니터링, 피드백 루프를 통해 빠르고 안정적인 소프트웨어 배포를 실현합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('성능 최적화 방법론을 설명해주세요.', 2, '병목지점 식별, 프로파일링, 알고리즘 개선, 캐싱 전략, 데이터베이스 최적화, 네트워크 최적화를 체계적으로 접근합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('분산 시스템 설계 고려사항을 설명해주세요.', 2, 'CAP 정리, 일관성 모델, 파티션 허용성, 장애 처리, 데이터 복제, 네트워크 분할에 대한 대응 전략을 수립해야 합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('마이크로서비스 도입 전략을 설명해주세요.', 2, '도메인 분해, 서비스 경계 설정, API 설계, 데이터 관리, 서비스 간 통신, 모니터링, 배포 전략을 종합적으로 고려합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('클라우드 네이티브 설계 원칙을 설명해주세요.', 2, '컨테이너화, 서비스 메시, 서버리스, 이벤트 드리븐 아키텍처, 관측 가능성을 통해 클라우드의 이점을 최대한 활용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('도메인 주도 설계(DDD) 적용 방법을 설명해주세요.', 2, '유비쿼터스 언어, 바운디드 컨텍스트, 애그리게이트, 엔티티, 값 객체를 활용하여 비즈니스 도메인에 맞는 소프트웨어를 설계합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('이벤트 소싱과 CQRS 패턴을 설명해주세요.', 2, '이벤트를 통한 상태 변경 추적과 명령과 조회의 분리를 통해 복잡한 비즈니스 로직을 효과적으로 관리합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('API 설계 베스트 프랙티스를 설명해주세요.', 2, 'RESTful 원칙, 버전 관리, 문서화, 보안, 에러 핸들링, 페이지네이션, 캐싱을 고려한 일관성 있는 API를 설계합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('테스트 전략과 자동화를 설명해주세요.', 2, '테스트 피라미드, TDD/BDD, 단위/통합/E2E 테스트, 테스트 더블, CI/CD 통합을 통해 품질 보증 체계를 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터 파이프라인 설계를 설명해주세요.', 2, 'ETL/ELT 프로세스, 스트림 처리, 배치 처리, 데이터 품질 관리, 모니터링을 통해 안정적인 데이터 처리 시스템을 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('보안 설계 원칙을 설명해주세요.', 2, '다층 보안, 최소 권한 원칙, 데이터 암호화, 인증/인가, 보안 감사, 취약점 관리를 통한 종합적인 보안 체계를 수립합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('장애 대응과 복구 전략을 설명해주세요.', 2, '장애 감지, 알림, 격리, 복구, 사후 분석을 통한 체계적인 장애 대응과 서비스 안정성 향상을 달성합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('기술 스택 선택 기준을 설명해주세요.', 2, '비즈니스 요구사항, 팀 역량, 생태계, 성능, 확장성, 유지보수성, 비용을 종합적으로 고려하여 최적의 기술을 선택합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('문서화 전략과 지식 관리를 설명해주세요.', 2, '아키텍처 문서, API 문서, 운영 가이드, 코드 주석, 위키를 통해 팀 지식을 체계적으로 관리하고 공유합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('개발자 온보딩 프로세스를 설명해주세요.', 2, '환경 설정, 코드베이스 이해, 도메인 지식 습득, 멘토링, 점진적 업무 할당을 통해 새로운 팀원의 빠른 적응을 돕습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('크로스 플랫폼 개발 전략을 설명해주세요.', 2, '공통 로직 추상화, 플랫폼별 특화 구현, 일관된 사용자 경험, 효율적인 리소스 관리를 통해 다중 플랫폼을 지원합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('국제화와 현지화 전략을 설명해주세요.', 2, '다국어 지원, 문화적 차이 고려, 시간대 처리, 통화 변환, 법적 요구사항 준수를 통해 글로벌 서비스를 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터 거버넌스 구축 방법을 설명해주세요.', 2, '데이터 품질 관리, 메타데이터 관리, 접근 권한 제어, 개인정보 보호, 규정 준수를 통해 데이터 자산을 체계적으로 관리합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('개발 생산성 향상 방법을 설명해주세요.', 2, '개발 환경 개선, 자동화 도구, 코드 생성, 템플릿, 라이브러리 활용을 통해 개발 효율성을 극대화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 스타트업 개발자 면접 질문들 추가 (질문 세트 18): 질문 337-366 (25개 추가)
('MVP 개발 전략을 설명해주세요.', 2, '핵심 기능에 집중하여 최소한의 기능으로 시장 검증을 빠르게 진행합니다. 사용자 피드백을 바탕으로 점진적으로 기능을 확장하며 제품-시장 적합성을 찾아갑니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('제한된 리소스로 개발하는 방법을 설명해주세요.', 2, '우선순위 설정, 오픈소스 활용, 클라우드 서비스 사용, 자동화 도구 도입, No-Code/Low-Code 플랫폼 활용을 통해 효율성을 극대화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('빠른 개발과 품질의 균형을 설명해주세요.', 2, '핵심 기능에 대한 테스트 우선, 코드 리뷰 간소화, 자동화된 배포, 모니터링 강화를 통해 속도와 품질을 동시에 확보합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('기술 스택 선택 기준을 설명해주세요.', 2, '팀의 기술 스택, 개발 속도, 확장성, 커뮤니티 지원, 비용, 학습 곡선을 종합적으로 고려하여 스타트업에 적합한 기술을 선택합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('사용자 피드백 수집과 반영 방법을 설명해주세요.', 2, '다양한 채널을 통한 피드백 수집, 빠른 분석과 우선순위 결정, 신속한 개발과 배포, 결과 측정을 통한 지속적인 제품 개선을 진행합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('스타트업에서의 DevOps 구축을 설명해주세요.', 2, '간단한 CI/CD 파이프라인, 클라우드 인프라 활용, 모니터링 도구 도입, 자동화 우선순위 설정을 통해 효율적인 개발/배포 환경을 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('확장성을 고려한 초기 설계를 설명해주세요.', 2, '모듈화된 아키텍처, 데이터베이스 설계 최적화, 캐싱 전략, API 설계, 마이크로서비스 고려를 통해 성장에 대비한 기반을 마련합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터 분석과 지표 관리를 설명해주세요.', 2, 'KPI 정의, 이벤트 트래킹, 사용자 행동 분석, A/B 테스트, 데이터 기반 의사결정을 통해 제품 성장을 위한 인사이트를 도출합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('보안과 컴플라이언스 대응을 설명해주세요.', 2, '기본적인 보안 수칙 준수, 개인정보 보호, HTTPS 적용, 정기적인 보안 점검을 통해 초기부터 보안 기반을 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('팀 협업과 커뮤니케이션을 설명해주세요.', 2, '애자일 방법론 적용, 일일 스탠드업, 효율적인 회의, 비동기 커뮤니케이션, 문서화를 통해 작은 팀에서의 생산성을 극대화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('사용자 중심 개발 방법론을 설명해주세요.', 2, '사용자 페르소나 정의, 사용자 여정 매핑, 사용성 테스트, 피드백 루프 구축을 통해 사용자 가치를 중심으로 한 개발을 진행합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('비즈니스 모델과 기술의 연계를 설명해주세요.', 2, '수익 모델 이해, 기술적 구현 방안 제시, 비용 효율성 고려, 확장 가능성 검토를 통해 비즈니스 성공을 뒷받침하는 기술을 개발합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('제품 로드맵과 개발 계획을 설명해주세요.', 2, '비즈니스 목표와 기술 로드맵 연계, 우선순위 기반 개발, 마일스톤 설정, 리스크 관리를 통해 전략적인 제품 개발을 진행합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('자동화와 도구 활용 전략을 설명해주세요.', 2, '반복 작업 자동화, 배포 자동화, 테스트 자동화, 모니터링 자동화를 통해 개발 팀의 생산성을 극대화하고 휴먼 에러를 최소화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('스타트업에서의 기술 부채 관리를 설명해주세요.', 2, '빠른 개발로 인한 기술 부채를 인정하고, 우선순위에 따라 계획적으로 해결하며, 비즈니스 성장과 코드 품질의 균형점을 찾습니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('글로벌 서비스 개발 고려사항을 설명해주세요.', 2, '다국어 지원, 시간대 처리, 현지화, 법적 요구사항, 성능 최적화를 초기부터 고려하여 글로벌 확장 가능한 서비스를 구축합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('오픈소스 전략과 활용을 설명해주세요.', 2, '검증된 오픈소스 라이브러리 활용, 라이선스 검토, 커뮤니티 기여, 자체 오픈소스 공개를 통해 개발 효율성과 브랜드 가치를 동시에 확보합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('성능 모니터링과 최적화를 설명해주세요.', 2, '핵심 지표 모니터링, 사용자 경험 추적, 병목지점 식별, 점진적 최적화를 통해 사용자 만족도를 높이고 이탈률을 감소시킵니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A/B 테스트와 실험 문화를 설명해주세요.', 2, '가설 수립, 실험 설계, 통계적 유의성 검증, 학습과 적용을 통해 데이터 기반의 제품 개선과 성장을 달성합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('채용과 팀 빌딩 전략을 설명해주세요.', 2, '문화적 적합성, 성장 가능성, 다양한 채용 채널 활용, 온보딩 프로세스 최적화를 통해 스타트업에 적합한 인재를 확보하고 유지합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('리스크 관리와 대응 전략을 설명해주세요.', 2, '기술적 리스크, 비즈니스 리스크, 시장 리스크를 식별하고, 예방책과 대응책을 수립하여 스타트업의 생존 가능성을 높입니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('투자와 기술의 관계를 설명해주세요.', 2, '기술적 차별화, 특허 가능성, 확장성 입증, 기술 로드맵 제시를 통해 투자자에게 기술적 가치를 효과적으로 전달합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('경쟁 분석과 차별화 전략을 설명해주세요.', 2, '경쟁사 기술 분석, 차별화 포인트 발굴, 기술적 우위 확보, 특허 전략을 통해 시장에서의 경쟁 우위를 창출합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('데이터 전략과 활용을 설명해주세요.', 2, '데이터 수집 체계 구축, 분석 인프라, 개인정보 보호, 데이터 기반 인사이트 도출을 통해 데이터를 핵심 자산으로 활용합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('브랜딩과 마케팅 기술 지원을 설명해주세요.', 2, 'SEO 최적화, 소셜 미디어 연동, 마케팅 자동화, 사용자 추천 시스템 구축을 통해 기술로 마케팅 효과를 극대화합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 질문-질문세트 매핑 데이터 생성
INSERT INTO question_set_question_maps (question_set_id, question_id, display_order, created_at, updated_at) VALUES
-- 질문 세트 1 (Java 백엔드): 질문 1-5
(1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 4, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 5, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 2 (React 프론트엔드): 질문 6-10
(2, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 7, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 10, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 3 (알고리즘): 질문 11-15
(3, 11, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 12, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 13, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 14, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 15, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 4 (DevOps): 질문 16-20
(4, 16, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 17, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 18, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 19, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 20, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 5 (데이터베이스): 질문 21-25
(5, 21, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 22, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 23, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 24, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 25, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 6 (모바일 앱 개발): 질문 26-30
(6, 26, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 27, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 28, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 29, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 30, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 7 (웹 보안): 질문 31-35
(7, 31, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 32, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 33, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 34, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 35, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 8 (머신러닝): 질문 36-40
(8, 36, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 37, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 38, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 39, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 40, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 9 (클라우드 아키텍처): 질문 41-45
(9, 41, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 42, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 43, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 44, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 45, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 10 (게임 개발): 질문 46-50
(10, 46, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 47, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 48, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 49, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 50, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 11 (네트워크 엔지니어링): 질문 51-55
(11, 51, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 52, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 53, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 54, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 55, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 12 (QA 테스팅): 질문 56-60
(12, 56, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 57, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 58, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 59, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 60, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 13 (UI/UX 디자인): 질문 61-65
(13, 61, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 62, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 63, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 64, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 65, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 14 (IT 프로젝트 관리): 질문 66-70
(14, 66, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 67, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 68, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 69, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 70, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 15 (시스템 관리): 질문 71-75
(15, 71, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 72, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 73, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 74, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 75, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 16 (주니어 개발자): 질문 76-80
(16, 76, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 77, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 78, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 79, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 80, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 17 (시니어 개발자): 질문 81-85
(17, 81, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 82, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 83, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 84, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 85, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 18 (스타트업 개발): 질문 86-90
(18, 86, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 87, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 88, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 89, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 90, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 19 (기업 개발): 질문 91-95
(19, 91, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 92, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 93, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 94, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 95, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 20 (AI 연구): 질문 96-100
(20, 96, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 97, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 98, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 99, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 100, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 21 (블록체인 개발): 질문 101-105
(21, 101, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 102, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 103, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 104, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 105, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 22 (IoT 개발): 질문 106-110
(22, 106, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 107, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 108, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 109, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 110, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 23 (빅데이터 엔지니어링): 질문 111-115
(23, 111, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 112, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 113, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 114, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 115, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 24 (사이버보안): 질문 116-120
(24, 116, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 117, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 118, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 119, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 120, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 25 (소프트웨어 아키텍처): 질문 121-125
(25, 121, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 122, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 123, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 124, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 125, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 26 (API 개발): 질문 126-130
(26, 126, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 127, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 128, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 129, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 130, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 27 (성능 최적화): 질문 131-135
(27, 131, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 132, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 133, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 134, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 135, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 28 (기술 리더십): 질문 136-140
(28, 136, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 137, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 138, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 139, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 140, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 29 (풀스택 개발): 질문 141-145
(29, 141, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 142, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 143, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 144, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 145, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- 질문 세트 30 (오픈소스 기여): 질문 146-150
(30, 146, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 147, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 148, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 149, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 150, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);