import { QuestionSet } from '@/entities/questionSet/model/type';

export const questionSetList: readonly QuestionSet[] = Object.freeze([
  {
    id: 1,
    nickname: '이찬',
    title: 'HTTP 기본',
    description: 'HTTP의 동작 원리와 특징에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 1, tag: 'HTTP' },
      { id: 2, tag: '네트워크' },
    ],
    questions: [
      {
        id: 1,
        content: 'HTTP의 GET과 POST 방식 차이는?',
        questionType: 'DEFAULT',
        questionAnswer: 'GET은 데이터를 URL에 포함, POST는 본문에 포함.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 2,
    nickname: '예은',
    title: '자바스크립트 비동기',
    description: 'JS의 비동기 처리 방식에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: false,
    tags: [
      { id: 2, tag: 'JavaScript' },
      { id: 3, tag: '브라우저' },
    ],
    questions: [
      {
        id: 2,
        content: 'Promise와 async/await 차이점은?',
        questionType: 'DEFAULT',
        questionAnswer:
          'async/await는 Promise를 더 직관적으로 사용할 수 있게 해줍니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 3,
    nickname: '재은',
    title: '브라우저 렌더링',
    description: '렌더링 엔진의 동작 방식 관련 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 3, tag: '브라우저' },
      { id: 4, tag: '네트워크' },
    ],
    questions: [
      {
        id: 3,
        content: '크리티컬 렌더링 패스란?',
        questionType: 'DEFAULT',
        questionAnswer:
          '브라우저가 화면을 그리기까지 거치는 일련의 과정입니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 4,
    nickname: '광민',
    title: 'TCP와 UDP',
    description: '전송 계층 프로토콜에 대한 비교 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 4, tag: '네트워크' },
      { id: 5, tag: 'REST' },
    ],
    questions: [
      {
        id: 4,
        content: 'TCP와 UDP의 차이는?',
        questionType: 'DEFAULT',
        questionAnswer: 'TCP는 연결 기반, UDP는 비연결 기반.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 5,
    nickname: '진',
    title: 'REST API 설계',
    description: 'RESTful API의 설계 원칙에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 5, tag: 'REST' },
      { id: 6, tag: '인증' },
    ],
    questions: [
      {
        id: 5,
        content: 'REST에서 리소스란 무엇인가요?',
        questionType: 'DEFAULT',
        questionAnswer: 'URI로 표현되는 자원을 의미합니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 6,
    nickname: '이찬',
    title: '쿠키와 세션',
    description: '웹 브라우저의 상태 유지 방식에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: false,
    tags: [
      { id: 6, tag: '인증' },
      { id: 7, tag: 'JavaScript' },
    ],
    questions: [
      {
        id: 6,
        content: '쿠키와 세션의 차이는?',
        questionType: 'DEFAULT',
        questionAnswer: '쿠키는 클라이언트에 저장, 세션은 서버에 저장.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 7,
    nickname: '예은',
    title: 'JS this 키워드',
    description: 'this 바인딩에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: false,
    tags: [
      { id: 7, tag: 'JavaScript' },
      { id: 8, tag: 'Java' },
    ],
    questions: [
      {
        id: 7,
        content: 'this가 가리키는 대상을 결정하는 기준은?',
        questionType: 'DEFAULT',
        questionAnswer: '호출 방식에 따라 달라집니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 8,
    nickname: '재은',
    title: 'Java OOP',
    description: '객체 지향의 4대 특성 관련 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 8, tag: 'Java' },
      { id: 9, tag: 'Git' },
    ],
    questions: [
      {
        id: 8,
        content: '다형성이란 무엇인가요?',
        questionType: 'DEFAULT',
        questionAnswer: '동일한 메서드가 다른 방식으로 동작하는 것.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 9,
    nickname: '광민',
    title: 'Git 기본',
    description: 'Git의 주요 명령어에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 9, tag: 'Git' },
      { id: 10, tag: 'CSS' },
    ],
    questions: [
      {
        id: 9,
        content: 'rebase와 merge 차이점은?',
        questionType: 'DEFAULT',
        questionAnswer: 'rebase는 히스토리를 깔끔하게, merge는 원본 보존.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 10,
    nickname: '진',
    title: 'CSS 선택자',
    description: 'CSS에서 다양한 선택자 사용법에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: false,
    tags: [
      { id: 10, tag: 'CSS' },
      { id: 11, tag: 'React' },
    ],
    questions: [
      {
        id: 10,
        content: '속성 선택자 예시는?',
        questionType: 'DEFAULT',
        questionAnswer: '[type="text"] 같은 형태입니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 11,
    nickname: '이찬',
    title: 'React 상태 관리',
    description: 'useState, useReducer 등 상태 관리 훅에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 11, tag: 'React' },
      { id: 12, tag: '웹 성능' },
    ],
    questions: [
      {
        id: 11,
        content: 'useReducer는 언제 사용하는 것이 좋나요?',
        questionType: 'DEFAULT',
        questionAnswer: '복잡한 상태 업데이트 로직이 필요할 때 유용합니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 12,
    nickname: '예은',
    title: 'CSR과 SSR 차이',
    description: '클라이언트/서버 사이드 렌더링 방식 비교 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: false,
    tags: [
      { id: 12, tag: '웹 성능' },
      { id: 13, tag: 'DB' },
      { id: 14, tag: '트랜잭션' },
      { id: 15, tag: '보안' },
    ],
    questions: [
      {
        id: 12,
        content: 'CSR과 SSR의 장단점은?',
        questionType: 'DEFAULT',
        questionAnswer: 'CSR은 초기 속도 느리나 UX 좋음, SSR은 반대.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 13,
    nickname: '재은',
    title: 'DB 정규화',
    description: '정규화의 목적과 단계에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 13, tag: 'DB' },
      { id: 14, tag: '트랜잭션' },
    ],
    questions: [
      {
        id: 13,
        content: '제1정규형이란 무엇인가요?',
        questionType: 'DEFAULT',
        questionAnswer: '속성 값이 원자값으로만 구성되어야 함.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 14,
    nickname: '광민',
    title: '트랜잭션과 ACID',
    description: '트랜잭션의 성질과 일관성 보장 방법에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 14, tag: 'DB' },
      { id: 15, tag: '보안' },
    ],
    questions: [
      {
        id: 14,
        content: 'ACID 원칙이란?',
        questionType: 'DEFAULT',
        questionAnswer: '원자성, 일관성, 고립성, 지속성을 의미합니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 15,
    nickname: '진',
    title: 'XSS와 CSRF',
    description: '대표적인 웹 보안 이슈에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 15, tag: '보안' },
      { id: 16, tag: '브라우저' },
    ],
    questions: [
      {
        id: 15,
        content: 'CSRF 공격은 어떤 식으로 발생하나요?',
        questionType: 'DEFAULT',
        questionAnswer: '사용자의 인증 정보를 도용해 의도치 않은 요청을 보냄.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 16,
    nickname: '이찬',
    title: '브라우저 저장소',
    description: '쿠키, 로컬스토리지, 세션스토리지의 차이점에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: false,
    tags: [
      { id: 16, tag: '브라우저' },
      { id: 17, tag: 'CSS' },
    ],
    questions: [
      {
        id: 16,
        content: '로컬스토리지와 세션스토리지의 차이는?',
        questionType: 'DEFAULT',
        questionAnswer:
          '세션스토리지는 탭 종료 시 삭제, 로컬스토리지는 영구 저장.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 17,
    nickname: '예은',
    title: 'CSS Flexbox',
    description: 'Flexbox의 주요 속성과 정렬 방식 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 17, tag: 'CSS' },
      { id: 18, tag: '보안' },
    ],
    questions: [
      {
        id: 17,
        content: 'justify-content 속성은 어떤 역할인가요?',
        questionType: 'DEFAULT',
        questionAnswer: '주 축 방향으로 정렬 방식을 지정합니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 18,
    nickname: '재은',
    title: 'JWT 인증',
    description: 'JWT 토큰 기반 인증 방식에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 18, tag: '보안' },
      { id: 19, tag: 'API' },
    ],
    questions: [
      {
        id: 18,
        content: 'JWT의 구조는 어떻게 되나요?',
        questionType: 'DEFAULT',
        questionAnswer: '헤더, 페이로드, 서명 세 부분으로 구성됩니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 19,
    nickname: '광민',
    title: 'API Rate Limit',
    description: 'API 사용량 제한 정책에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: false,
    tags: [
      { id: 19, tag: 'API' },
      { id: 20, tag: 'DevOps' },
    ],
    questions: [
      {
        id: 19,
        content: 'Rate Limiting은 왜 필요한가요?',
        questionType: 'DEFAULT',
        questionAnswer:
          '서비스 오용 방지 및 안정적인 성능 유지를 위해 필요합니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
  {
    id: 20,
    nickname: '진',
    title: 'CI/CD 개념',
    description: 'CI/CD의 개념과 파이프라인 구성에 대한 질문입니다.',
    versionNumber: 1,
    parentVersionId: null,
    isShared: true,
    tags: [
      { id: 20, tag: 'DevOps' },
      { id: 21, tag: '클라우드' },
    ],
    questions: [
      {
        id: 20,
        content: 'CI와 CD의 차이는?',
        questionType: 'DEFAULT',
        questionAnswer: 'CI는 코드 통합 자동화, CD는 배포 자동화를 의미합니다.',
        displayOrder: 1,
        tailQuestions: [],
      },
    ],
  },
]);
